name: Update README

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements file

      - name: Run script
        run: |
          python your_script.py

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update README [skip ci]"
          git push
